USE revex_insights;
INSERT INTO department (department_id, department_name, department_name_key) VALUES (103, 'Innovation and Performance', 'INNOVATION_AND_PERFORMANCE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (107, 'Department of Finance', 'DEPARTMENT_OF_FINANCE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (230, 'Department of Public Safety - Police', 'DEPARTMENT_OF_PUBLIC_SAFETY_POLICE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (250, 'Department of Public Safety - Fire', 'DEPARTMENT_OF_PUBLIC_SAFETY_FIRE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (420, 'Department of Public Works - Operations', 'DEPARTMENT_OF_PUBLIC_WORKS_OPERATIONS');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (500, 'Parks and Recreation', 'PARKS_AND_RECREATION');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (101, 'City Council', 'CITY_COUNCIL');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (112, 'City Clerk', 'CITY_CLERK');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (102, 'Mayor's Office', 'MAYORS_OFFICE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (105, 'Human Relations Commission', 'HUMAN_RELATIONS_COMMISSION');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (106, 'Controller's Office', 'CONTROLLERS_OFFICE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (108, 'Department of Law', 'DEPARTMENT_OF_LAW');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (109, 'Personnel/Civil Service', 'PERSONNEL_AND_CIVIL_SERVICE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (110, 'Department of City Planning', 'DEPARTMENT_OF_CITY_PLANNING');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (130, 'Permits Licenses and Inspection', 'PERMITS_LICENSES_AND_INSPECTION');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (210, 'Department of Public Safety - Administration', 'DEPARTMENT_OF_PUBLIC_SAFETY_ADMINISTRATION');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (240, 'Office of Municipal Investigations', 'OFFICE_OF_MUNICIPAL_INVESTIGATIONS');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (280, 'Department of Public Safety - Animal Care and Control', 'DEPARTMENT_OF_PUBLIC_SAFETY_ANIMAL_CARE_AND_CONTROL');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (410, 'Department of Public Works - Administration', 'DEPARTMENT_OF_PUBLIC_WORKS_ADMINISTRATION');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (430, 'Department of Public Works - Environmental Services', 'DEPARTMENT_OF_PUBLIC_WORKS_ENVIRONMENTAL_SERVICES');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (450, 'Department of Public Works - Facilities', 'DEPARTMENT_OF_PUBLIC_WORKS_FACILITIES');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (600, 'Mobility and Infrastructure', 'MOBILITY_AND_INFRASTRUCTURE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (400, 'Public Works', 'PUBLIC_WORKS');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (122, 'Office of Management and Budget', 'OFFICE_OF_MANAGEMENT_AND_BUDGET');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (220, 'Department of Public Safety - Emergency Medical Services', 'DEPARTMENT_OF_PUBLIC_SAFETY_EMERGENCY_MEDICAL_SERVICES');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (820, 'Urban Redevelopment Authority Projects', 'URBAN_REDEVELOPMENT_AUTHORITY_PROJECTS');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (840, 'Equipment Leasing Authority', 'EQUIPMENT_LEASING_AUTHORITY');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (183, 'Equal Opportunity Review Committee', 'EQUAL_OPPORTUNITY_REVIEW_COMMITTEE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (121, 'Finance, Procurement and Fleet', 'FINANCE_PROCUREMENT_AND_FLEET');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (440, 'Department of Public Works - Transportation and Engine', 'DEPARTMENT_OF_PUBLIC_WORKS_TRANSPORTATION_AND_ENGINE');
INSERT INTO department (department_id, department_name, department_name_key) VALUES (270, 'Department of Public Safety - Building Inspection', 'DEPARTMENT_OF_PUBLIC_SAFETY_BUILDING_INSPECTION');