USE data_viz_hub;
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (11101, 'General Fund', 'GENERAL_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28050, 'Senior Citizens Program Trust Fund', 'SENIOR_CITIZENS_PROGRAM_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28020, 'Equal Employment Opportunity Commission Trust Fund', 'EQUAL_EMPLOYMENT_OPPORTUNITY_COMMISSION_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29040, 'Grants Fund', 'GRANTS_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24067, 'Police Secondary Employment Trust Fund', 'POLICE_SECONDARY_EMPLOYMENT_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28033, 'Mellon Park Tennis Trust Fund', 'MELLON_PARK_TENNIS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28003, 'Allegheny Regional Asset District Public Works', 'ALLEGHENY_REGIONAL_ASSET_DISTRICT_PUBLIC_WORKS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26030, 'Housing and Urban Development Fair Housing Program Trust Fund', 'HOUSING_AND_URBAN_DEVELOPMENT_FAIR_HOUSING_PROGRAM_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28055, 'Special Summer Food Service Trust Fund', 'SPECIAL_SUMMER_FOOD_SERVICE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28004, 'Allegheny Regional Asset District Parks', 'ALLEGHENY_REGIONAL_ASSET_DISTRICT_PARKS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (23000, 'Job Training Partnership Act', 'JOB_TRAINING_PARTNERSHIP_ACT');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78765, 'Tree Taxing Bodies', 'TREE_TAXING_BODIES');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26010, 'Community Development Block Grant Fund', 'COMMUNITY_DEVELOPMENT_BLOCK_GRANT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24037, 'Emergency Medical Services Reimbursement Events Trust Fund', 'EMERGENCY_MEDICAL_SERVICES_REIMBURSEMENT_EVENTS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78768, 'Three Taxing Bodies Escrow Trust Fund', 'THREE_TAXING_BODIES_ESCROW_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (32000, 'Debt Service Project Fund', 'DEBT_SERVICE_PROJECT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24016, 'Confiscated Narcotics Proceeds', 'CONFISCATED_NARCOTICS_PROCEEDS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26020, 'Emergency Shelters Program Trust Fund', 'EMERGENCY_SHELTERS_PROGRAM_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28070, 'Solid Waste Trust Fund', 'SOLID_WASTE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28043, 'Public Works Trust Fund', 'PUBLIC_WORKS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28053, 'Shade Tree Trust Fund', 'SHADE_TREE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40120, '2020 Pay-As-You-Go', '2020_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29060, 'Special Parks Program Great Race', 'SPECIAL_PARKS_PROGRAM_GREAT_RACE');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (75020, 'Workers Compensation Commutations', 'WORKERS_COMPENSATION_COMMUTATIONS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78160, 'Voluntary Employees Beneficiary Association Health Insurance', 'VOLUNTARY_EMPLOYEES_BENEFICIARY_ASSOCIATION_HEALTH_INSURANCE');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78170, 'Voluntary Employees Beneficiary Association Workers Compensation', 'VOLUNTARY_EMPLOYEES_BENEFICIARY_ASSOCIATION_WORKERS_COMPENSATION');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40017, 'Project Fund 2017 Bond', 'PROJECT_FUND_2017_BOND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40018, 'Project Fund 2018 Bond', 'PROJECT_FUND_2018_BOND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40119, '2019 Pay-As-You-Go', '2019_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40019, 'Project Fund 2019 Bond', 'PROJECT_FUND_2019_BOND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40118, '2018 Pay-As-You-Go', '2018_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24063, 'Pennsylvania Emergency Management Agency and Homeland Security', 'PENNSYLVANIA_EMERGENCY_MANAGEMENT_AGENCY_AND_HOMELAND_SECURITY');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28085, 'Green Initiative Trust Fund', 'GREEN_INITIATIVE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40001, 'Capital Project Fund', 'CAPITAL_PROJECT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28045, 'Schenley Park Rink Trust Fund', 'SCHENLEY_PARK_RINK_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (22000, 'Liquid Fuels Tax', 'LIQUID_FUELS_TAX');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40116, '2016 Pay-As-You-Go', '2016_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40020, 'Project Fund 2020 Bond', 'PROJECT_FUND_2020_BOND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40114, 'Transportation Improvement Program Projects', 'TRANSPORTATION_IMPROVEMENT_PROGRAM_PROJECTS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78540, 'Fire Escrow', 'FIRE_ESCROW');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40012, 'Project Fund 2012 Bond', 'PROJECT_FUND_2012_BOND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78590, 'Real Estate Tax Refunds City', 'REAL_ESTATE_TAX_REFUNDS_CITY');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40117, '2017 Pay-As-You-Go', '2017_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78595, 'Real Estate Tax Refunds School', 'REAL_ESTATE_TAX_REFUNDS_SCHOOL');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78740, 'Employee Travel Expense Advance Trust Fund', 'EMPLOYEE_TRAVEL_EXPENSE_ADVANCE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78728, 'Demolition Trust Fund', 'DEMOLITION_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24041, 'Hazardous Materials Trust Fund', 'HAZARDOUS_MATERIALS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40014, '2014 Pay-As-You-Go', '2014_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24084, 'Crossing Guard Special Events', 'CROSSING_GUARD_SPECIAL_EVENTS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78750, 'Pittsburgh Code Trust Fund', 'PITTSBURGH_CODE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24069, 'Public Safety Training Trust Fund', 'PUBLIC_SAFETY_TRAINING_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40115, '2015 Pay-As-You-Go', '2015_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24019, 'Confiscated Non-Narcotics Proceeds', 'CONFISCATED_NON_NARCOTICS_PROCEEDS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24009, 'Code Trust Fund', 'CODE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24046, 'Microfilm Permit Plans Trust Fund', 'MICROFILM_PERMIT_PLANS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28040, 'Pittsburgh Commission on Human Relations Trust Fund', 'PITTSBURGH_COMMISSION_ON_HUMAN_RELATIONS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28080, 'Verizon Franchise Trust Fund', 'VERIZON_FRANCHISE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40011, 'Capital Projects 2006 Bond', 'CAPITAL_PROJECTS_2006_BOND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24049, 'Mounted Police Trust Fund', 'MOUNTED_POLICE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24042, 'Graffiti Trust Fund', 'GRAFFITI_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24800, 'South Side Parking Enhancement', 'SOUTH_SIDE_PARKING_ENHANCEMENT');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28015, 'Comcast Franchise Trust Fund', 'COMCAST_FRANCHISE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29080, 'Frick Park Trust Fund', 'FRICK_PARK_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29065, 'Public Safety Support Trust Fund', 'PUBLIC_SAFETY_SUPPORT_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78400, 'Escheat Fund', 'ESCHEAT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29070, 'District 9 Crime Prevention', 'DISTRICT_9_CRIME_PREVENTION');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26050, 'Housing Opportunities for Persons With AIDS', 'HOUSING_OPPORTUNITIES_FOR_PERSONS_WITH_AIDS');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (40013, '2013 Pay-As-You-Go', '2013_PAY_AS_YOU_GO');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24040, 'Federal Task Force Trust Fund', 'FEDERAL_TASK_FORCE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24081, 'York County Planning Commission Mayor''s Youth Initiative Trust Fund', 'YORK_COUNTY_PLANNING_COMMISSION_MAYORS_YOUTH_INITIATIVE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26060, 'Appalachian Regional Commission', 'APPALACHIAN_REGIONAL_COMMISSION');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28067, 'Workforce Development Fund', 'WORKFORCE_DEVELOPMENT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28064, 'Stormwater Management Trust Fund', 'STORMWATER_MANAGEMENT_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24025, 'Drug Abuse Resistance Education Trust Fund', 'DRUG_ABUSE_RESISTANCE_EDUCATION_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26080, 'Brownfield Economic Development Fund', 'BROWNFIELD_ECONOMIC_DEVELOPMENT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78137, 'Other Post-Employment Benefits Trust Fund Police', 'OTHER_POST_EMPLOYMENT_BENEFITS_TRUST_FUND_POLICE');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24060, 'Operation Weed and Seed Fund', 'OPERATION_WEED_AND_SEED_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29075, 'Facilities Trust Fund', 'FACILITIES_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28065, 'Wayfinders Signage Trust Fund', 'WAYFINDERS_SIGNAGE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24006, 'Criminal Intelligence Fund', 'CRIMINAL_INTELLIGENCE_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26040, 'State Emergency Shelter Program', 'STATE_EMERGENCY_SHELTER_PROGRAM');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78138, 'Other Post-Employment Benefits Trust Fund Fire', 'OTHER_POST_EMPLOYMENT_BENEFITS_TRUST_FUND_FIRE');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28037, 'Phipps Conservatory Fund', 'PHIPPS_CONSERVATORY_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24030, 'Auto Theft Task Force II Trust Fund', 'AUTO_THEFT_TASK_FORCE_II_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24062, 'Pittsburgh Area National Geospatial-Intelligence Agency Trust Fund', 'PITTSBURGH_AREA_NATIONAL_GEOSPATIAL_INTELLIGENCE_AGENCY_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78769, 'Vending Trust Fund Controller', 'VENDING_TRUST_FUND_CONTROLLER');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78535, 'Ethics Board Trust Fund', 'ETHICS_BOARD_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78570, 'Earned Income Tax Refunds City', 'EARNED_INCOME_TAX_REFUNDS_CITY');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24045, 'Local Law Enforcement Fund', 'LOCAL_LAW_ENFORCEMENT_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24043, 'Highway Safety Trust Fund', 'HIGHWAY_SAFETY_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (24070, 'Rental Permit Trust Fund', 'RENTAL_PERMIT_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28063, 'Open Space Trust Fund', 'OPEN_SPACE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78575, 'Earned Income Tax Refunds School', 'EARNED_INCOME_TAX_REFUNDS_SCHOOL');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29050, 'Stimulus Fund', 'STIMULUS_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78135, 'Other Post-Employment Benefits Trust Fund', 'OTHER_POST_EMPLOYMENT_BENEFITS_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (29074, 'Liberty Avenue Bike Lane Grant', 'LIBERTY_AVENUE_BIKE_LANE_GRANT');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (26090, 'Homelessness Prevention and Rapid Re-Housing Program', 'HOMELESSNESS_PREVENTION_AND_RAPID_RE_HOUSING_PROGRAM');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (28060, 'Swimming Pool Maintenance Trust Fund', 'SWIMMING_POOL_MAINTENANCE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (12881, 'Copier Management and Postage Trust Fund', 'COPIER_MANAGEMENT_AND_POSTAGE_TRUST_FUND');
INSERT INTO fund (fund_id, fund_description, fund_description_key) VALUES (78722, 'Controller''s Financial Management Information System', 'CONTROLLERS_FINANCIAL_MANAGEMENT_INFORMATION_SYSTEM');
